#!/usr/sbin/env bash
#
# Simple script to link dots
#

declare -a MISC=(".bashrc" ".bash_aliases" ".bash_profile" ".Xresources" ".xinitrc")

# Link files in .config
echo "Linking config files"
while read -r file; do
  ln -sf "$PWD/${file#./}" "$HOME/${file#./}"
done <<< "$(find "./.config" -type f)"
echo

# Link misc files
echo "Linking misc files"
for file in "${MISC[@]}"; do
  ln -sf "$PWD/$file" "$HOME/$file"
done
echo

echo "Copying /etc files"
while read -r file; do
  sudo cp -i "$PWD/${file#./}" "/${file#./}"
  sudo chmod 0644 "/${file#./}"
done <<< "$(find "./etc" -type f)"
echo

echo "Linking themes"
for dir in $(find "./.themes" -maxdepth 1 -type d | sed 1d); do
  [ -L "$HOME/${dir#./}" ] && rm -f "$HOME/${dir#./}"
  ln -sf "$PWD/${dir#./}" "$HOME/${dir#./}"
done
echo

echo "Linking icons"
for dir in $(find "./.icons" -maxdepth 1 -type d | sed 1d); do
  [ -L "$HOME/${dir#./}" ] && rm -f "$HOME/${dir#./}"
  ln -sf "$PWD/${dir#./}" "$HOME/${dir#./}"
done
echo

echo "Linking .bin"
[ -L "$HOME/.bin" ] && rm -f "$HOME/.bin"
ln -sf "$PWD/.bin" "$HOME/.bin"

echo "Done!"
exit 0
