#!/bin/bash
#
# kbd_color: Let's me set my keyboard color easily
#
# Usage: kbd_color -d / <color>


KBD_BACKLIGHT_PATH=/sys/devices/platform/tuxedo_keyboard/color_left
DEFAULT="984673"

error_exit() {
	echo "Invalid color '$1'"
	exit 1
}

set_kbd_color() {
	echo "0x$1" >"$KBD_BACKLIGHT_PATH"
	exit 0
}

if [[ -n "$1" ]]; then
  if [[ "$1" =~ ^-d|-D$ ]]; then
    set_kbd_color "$DEFAULT"
  elif [[ "$1" =~ ^[a-fA-F0-9]{6}$ ]]; then
		set_kbd_color "$1"
	else
		error_exit "$1"
	fi
else
	read -rp "Enter a 6-char HEX color: " HEX_COLOR
	if [[ "$HEX_COLOR" =~ ^[a-fA-F0-9]{6}$ ]]; then
		set_kbd_color "$HEX_COLOR"
	else
		error_exit "$HEX_COLOR"
	fi
fi

exit 0

# EOF
