#!/usr/sbin/env bash

# If no lock screen in cache, update first
if [[ -d "$HOME/.cache/i3lock/current/" ]]; then
  betterlockscreen -l
  exit 0
else
  betterlockscreen -u "$BG_IMAGE" -r 1920x1080 -b 2
  betterlockscreen -l
  exit 0
fi
