#!/usr/bin/env bash

LIST="$HOME/.cache/anime"
declare -A ANIMES

[[ -z "$LIST" ]] && touch "$LIST"

list_eps() {
	local counter=0
	while read -r line; do
		((counter++))
		ANIMES[${line%% *}]="${line##* }"
		printf "\e[1;33m%s \e[1;32m%s\e[0m\n" "$counter" "$line"
	done <"$LIST"
}

update_list() {
	{
		for ANIME in "${!ANIMES[@]}"; do
			echo "$ANIME" "${ANIMES[$ANIME]}"
		done
	} >"$LIST"
}

clean_exit() {
  clear
  printf "\e[1;33mListing Unchanged.\e[0m\n\n"
  list_eps
  exit 0
}

trap clean_exit 2
{
	clear
	printf "\e[1;33mEpisode Tracker\e[0m\n\n"
	list_eps
	printf "\nEnter anime and new episode: "
	read -r ep_to_update ep
	ANIMES[$ep_to_update]="$ep"

	if [[ -z "$ep" ]]; then
		printf "\n\e[1;31mMust include an episode number!\n"
		exit 1
	fi

	if [[ "$ep" =~ clear ]]; then
		printf "\n\e[1;31mDeleted %s\n" "$ep_to_update"
		unset "ANIMES[$ep_to_update]"
		update_list
		exit 0
	fi

	update_list
	printf "\n\e[1;32mSuccess! Updated anime \e[1;33m%s \e[1;32mto episode \e[1;33m%s\n" "$ep_to_update" "$ep"
}
