#!/bin/bash

MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness)
BRIGHTNESS_FILE=/sys/class/backlight/intel_backlight/brightness
STEP=100

# Simple setting function
function set_brightness() {
	echo "$1" >"${BRIGHTNESS_FILE}"
	exit 0
}

function get_brightness() {
	cat "${BRIGHTNESS_FILE}"
}

function change_brightness() {
	local current_level
	local new_level

	current_level="$(get_brightness)"

	if [[ "$1" == "up" ]]; then
		new_level=$((current_level + STEP))
		if ((new_level > MAX)); then
			set_brightness "${MAX}"
		else
			set_brightness "${new_level}"
		fi
	elif [ "$1" = "down" ]; then
		new_level=$((current_level - STEP))
		if ((new_level < 0)); then
			set_brightness 0
		else
			set_brightness "${new_level}"
		fi
	fi

}

function print_usage() {
	local program_name

	program_name=$(basename "$0")

	cat <<_EOF_ >&2
Usage: 
	$program_name up
	$program_name down
_EOF_
}

case "$1" in
"-h" | "--help")
	print_usage
	;;
*)
	change_brightness "$1"
	;;
esac
