#!/bin/bash

DLDIR="$HOME/Downloads"

transmission-daemon \
	-c "$DLDIR" \
	--encryption-preferred \
	--download-dir "$DLDIR" \
	--global-seedratio 1:1

find "$DLDIR" -type f -iname "*.torrent" \
	-exec transmission-remote --add '{}' \
	--get all --download-dir "$DLDIR" \;

print_torrents() {
	printf "\e[1;33m%s\e[0m\n\n" "Bittorrent Downloader"
	printf "\e[0;31m%s\t\t\t%s\t%s\e[0m\n" "Status & Name" "Percent" "Time Remaining"

	while read -r num pcent size sunit time tunit up down ratio name; do
		[[ "$num" =~ ^Sum ]] && break
		if [[ "$time" == "Unknown" ]]; then
			time="Done"
			tunit=""
		fi
		printf "%s\t%s\t%s\n" "${name:0:28}..." "$pcent" "$time $tunit"
	done <<<"$(transmission-remote -l | sed 1d)"
}

while true; do
  clear
	print_torrents
	sleep 5
done
