#!/bin/sh
xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal \
  --output eDP-1-1 --mode 1920x1080 --pos 3840x1080 --rotate normal
xsetroot -cursor_name left_ptr &
bspc wm -r
