#!/bin/bash
#

declare -i length

length=32
simple=0

if [[ "$1" == "-s" ]]; then
	simple=1
fi

node <<EOF

const crypto = require('crypto');
const { Readable } = require('stream');

if ($simple) {
	Readable.from(crypto.randomBytes(${length}).toString('base64url')).pipe(process.stdout);
} else {
	const specialCharacter = '!@#\_-$%&*:;'
	const randomBytes = crypto.randomBytes(${length}).toString('base64url');
	const shouldAddChar = () => Math.round(Math.random() * 3) === 2;
	const addChar = () => shouldAddChar() && specialCharacter[Math.floor(Math.random() * specialCharacter.length)];
	const zipped = [...randomBytes].flatMap(char => [char, addChar()]).filter(Boolean);

	Readable.from(zipped).pipe(process.stdout);
}

EOF
