#!/bin/bash

# usage provides usage information
usage() {
  echo "Usage: $0 [scriptname]"
}

# create_script creates a new script file and opens it
create_script() {
  echo '#!/bin/bash' > "$1"
  chmod +x "$1"
  if [[ $EDITOR ]]; then
    "$EDITOR" "$1"
  else
    vim "$1"
  fi
}

# ensure the correct number of arguments
if [[ ! "$1" || "$#" -gt 1 ]]; then
  usage
  exit 1
fi

# verifies if a file already exists
if [[ -e "$1" ]]; then
  read -rp "Overwrite file? [y/n] "
  if [[ "$REPLY" =~ ^(y|Y)$ ]]; then
    create_script "$1"
  else
    echo 'Aborted.'
    exit 0
  fi
else
  create_script "$1"
fi
