#!/bin/sh

case "$(file -b --mime-type "$1")" in
text/* | application/json)
	kitty -e bash -c "vim $1" &
	;;
application/pdf | application/epub*)
	zathura "$1" &
	;;
video/* | audio/*)
	mpv "$1" &
	;;
image/*)
	ristretto "$1" &
	;;
application/*opendocument*)
	libreoffice "$1" &
	;;
*) ;;
esac
