#!/bin/bash

function run_init_script() {
	git clone 'https://github.com/astridlyre/react-jest-parcel-starter' "${TARGET_DIR}"
	cd "${TARGET_DIR}" || exit 1
	rm -rf '.git'
	git init
	pnpm install
	exit 0
}

TARGET_DIR="${1:-.}"
FORCE="${2}"

if [[ -d ${TARGET_DIR} && -z ${FORCE} ]]; then
	printf 'Target directory %s exists! Aborting. To force, use --force option' "${TARGET_DIR}"
	exit 1
fi

if [[ -d ${TARGET_DIR} && -n ${FORCE} && (${FORCE} =~ --force) && (${FORCE} != '/') ]]; then
	rm -rf "${TARGET_DIR}"
	run_init_script
elif [[ ! -d ${TARGET_DIR} ]]; then
	run_init_script
fi

exit 1
