#!/bin/bash

# scriptbc: Wrapper for 'bc' that returns the result of a calculation

if [[ "$1" == "-p" ]]; then
  precision="$2"
  shift 2
else
  precision=2 # Default
fi

input="$3"

if [[ ! "$input" ]]; then
  input="$(< /dev/stdin)"
fi

bc -q -l << EOF
scale=$precision
$input
quit
EOF

exit 0

