#!/usr/sbin/env bash

MODULES="$HOME/.cache/.sound-modules"

get_microphone() {
  local microphone
  microphone="$(pactl list sources | grep -E -o 'Name: .*' | grep -E -v '.*.monitor')"
  microphone=${microphone//Name: /}
  echo "$microphone"
}

get_speakers() {
  local speakers
  speakers="$(pactl list sinks | grep -E -o 'Name: .*')"
  speakers=${speakers//Name: /}
  echo "$speakers"
}

microphone="$(get_microphone)"
speakers="$(get_speakers)"

enable_stream() {
	pactl load-module module-null-sink sink_name=virtual1 \
    sink_properties=device.description="virtual1"
	pactl load-module module-null-sink sink_name=virtual2 \
    sink_properties=device.description="virtual2"

  pactl load-module module-loopback source=virtual1.monitor sink="$speakers" \
    latency_msec=1
  pactl load-module module-loopback source=virtual1.monitor sink=virtual2 \
    latency_msec=1
  pactl load-module module-loopback source="$microphone" sink=virtual2 \
    latency_msec=1
}

disable_stream() {
  echo "Unloading Modules"
  while read -r mod; do
    pactl unload-module "$mod"
  done < "$MODULES"
  echo "" > "$MODULES"
}

usage() {
  echo "Usage: $(basename "$0") [on|off]"
  exit 1
}

case "$1" in
on) enable_stream > "$MODULES";;
off) disable_stream ;;
*) usage ;;
esac
