#!/usr/sbin/env bash

MODULES="$HOME/.cache/.sound-modules"
MICROPHONE="alsa_input.pci-0000_00_1f.3.analog-stereo"
SPEAKERS="alsa_output.pci-0000_00_1f.3.analog-stereo"

enable_stream() {
  echo "Loading modules..."
	pactl load-module module-null-sink sink_name=from_sources \
    sink_properties=device.description="from_sources"
	pactl load-module module-null-sink sink_name=to_share \
    sink_properties=device.description="to_share"

  pactl load-module module-loopback source=from_sources sink="$SPEAKERS" \
    latency_msec=30
  pactl load-module module-loopback source=from_sources sink=to_share \
    latency_msec=30
  pactl load-module module-loopback source="$MICROPHONE" sink=to_share \
    latency_msec=30

  echo "Done."
}

disable_stream() {
  echo "Restarting Pipewire..."
  killall pipewire
  echo "Done."
}

usage() {
  echo "Usage: $(basename "$0") [on|off]"
  exit 1
}

case "$1" in
on) enable_stream > "$MODULES";;
off) disable_stream ;;
*) usage ;;
esac
