#!/bin/bash

npm install --global pnpm neovim

DEFAULT_PACKAGES=("bash-language-server"
	"prettier"
	"pyright"
	"typescript@next"
	"typescript-language-server"
	"vim-language-server"
	"vscode-langservers-extracted"
	"cssmodules-language-server"
	"emmet-ls"
	"yaml-language-server"
	"fixjson"
	"dockerfile-language-server-nodejs"
	"eslint_d"
	"write-good"
	"eslint"
	"autocannon"
	"esbuild"
	"@fsouza/prettierd")

pnpm install --global "${DEFAULT_PACKAGES[@]}"
