#!/bin/bash

npm install --global pnpm neovim

DEFAULT_PACKAGES=("bash-language-server"
	"@bitwarden/cli"
	"prettier"
	"pyright"
	"typescript"
	"typescript-language-server"
	"@typescript-eslint/parser"
	"@typescript-eslint/eslint-plugin"
	"vim-language-server"
	"vscode-langservers-extracted"
	"cssmodules-language-server"
	"@tailwindcss/language-server"
	"emmet-ls"
	"yaml-language-server"
	"fixjson"
	"dockerfile-language-server-nodejs"
	"eslint_d"
	"write-good"
	"eslint"
	"eslint-plugin-react"
	"eslint-plugin-jsx-a11y"
	"eslint-plugin-react-hooks"
	"eslint-plugin-import"
	"eslint-plugin-prettier"
	"autocannon"
	"@fsouza/prettierd")

pnpm install --global "${DEFAULT_PACKAGES[@]}"
