#!/bin/bash

DEFAULT_PACKAGES=("bash-language-server"
	"eslint_d"
	"live-server"
	"neovim"
	"prettier"
	"pyright"
	"typescript"
	"typescript-language-server"
	"vim-language-server"
	"vscode-css-languageserver-bin"
	"vscode-html-languageserver-bin"
	"vscode-json-languageserver"
	"yaml-language-server"
	"markdownlint"
	"fixjson"
    "dockerfile-language-server-nodejs"
    "emmet-ls"
	"@bitwarden/cli")

npm i -g "${DEFAULT_PACKAGES[@]}"
