#!/bin/bash

# -------------------------
# Error handler
# -------------------------
error_exit() {
	echo "update-neovim: ${1:- "Unknown Error"}" 1>&2
	exit 1
}

# -------------------------
# Update Neovim
# -------------------------
update_binary() {
	echo "Updating neovim"

	local scripts_path="$HOME/.bin"
	local app_image="$PWD/nvim.appimage"

	if wget -nv "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"; then
		chmod 755 "$app_image" || error_exit "Unable to change file permissions"
		mv "$app_image" "$scripts_path/nvim" || error_exit "Unable to move file"
		sudo ln -sf "$scripts_path/nvim" /usr/bin/vim || error_exit "Unable to link file"
		echo "Update complete"
	else
		error_exit "Update failed, unable to download file"
	fi
	echo "Updated neovim binary"
	return 0
}

update_plugins() {
	echo "Updating plugins"

	local plugins_path="$HOME/.local/share/nvim/site/pack/packer/start"
	local current_dir="$PWD"

	cd "$plugins_path" || error_exit "Unable to cd"

	for dir in *; do
		echo "Updating $dir"
		cd "./$dir" || error_exit "Unable to cd"
		git pull
		cd ..
	done

	echo "Updated plugins"
	cd "$current_dir" || error_exit "Unable to cd back"
	return 0
}

sudo -v
{ coproc { update_plugins || error_exit "Unable to update plugins"; } 2>&1 1>&3; } 3>&1
update_binary || error_exit "Unable to update binary"
wait
echo
exit 0
