#!/bin/bash

echo -n "Directory to scan? "
read -r SCANDIR
echo "Scanning $SCANDIR"

if [[ ! -d "/tmp/trash" ]]; then
	mkdir /tmp/trash
	echo "Creating temp trash directory"
fi

clamscan --infected --recursive --move="/tmp/trash" "$SCANDIR"
