#!/usr/bin/env bash

ZIRCUS_DIR=~/projects/zircus

cd $ZIRCUS_DIR || exit
tmux new-session -d -n Zircus rollup -c --watch
tmux split-window -h bundle exec jekyll build --watch
tmux split-window -v live-server _site/
tmux split-window -v bzircus
tmux -2 attach-session -d
