#=============================================================================
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    # guifont = "JetBrains Mono Medium:h15"
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    escape_key_binding = 'jk'
    enable_neomake = false
		snippet_engine = "ultisnips"
    project_rooter_outermost = false
		bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    default_indent = 2
    expand_tab = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 15

[[layers]]
name = "lsp"

[[layers]]
name = "fzf"

# [[layers]]
# name = "lang#javascript"

[[layers]]
name = "lang#go"
format_on_save = true

# [[layers]]
# name = 'lang#html'

[[layers]]
name = 'git'

[[layers]]
name = "format"
enable = false

[[custom_plugins]]
repo = "nvim-treesitter/nvim-treesitter"
merged = true
