#!/bin/bash

# History
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000

# Editor is vim
export VISUAL="/usr/bin/vim"
export EDITOR="/usr/bin/vim"
export FCEDIT="/usr/bin/vim"

# Use bat as a pager
export PAGER="bat --color=always --decorations=never --paging=always --theme=ansi"

# Man pages
export MANPAGER="less"
export MANWIDTH=110

# Less
export LESS='-J -i -x4'
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;33m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export TERM=wezterm

# Shell for keybinds
export SXHKD_SHELL=/bin/sh

# GPG and SSH
unset SSH_AGENT_PID
if ((${gnupg_SSH_AUTH_SOCK_by:-0} != $$)); then
	declare -x SSH_AUTH_SOCK
	SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Update startup TTY
GPG_TTY="$(tty)"
gpg-connect-agent updatestartuptty /bye &>/dev/null
export GPG_TTY

# No mailcheck
export MAILCHECK=off

# Go
export GOPATH=""
export GO111MODULE="on"

# IP Regexp
export MATCH_IP='([0-9]{1,3}\.){3}[0-9]{1,3}'

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# bat theme
export BAT_THEME='ansi'

# nnn
export NNN_COLORS='5555'
export NNN_FCOLORS='0A0B0C02000D0E0809030601'
export NNN_OPENER='nnn_opener'
export NNN_PLUG='s:suedit'
export NNN_TMPFILE="$HOME/.config}/nnn/.lastd"

# fzf directories to ignore
FZF_IGNORE_DIRS=(".git" "build" "node_modules" ".fzf" ".npm-packages" "vendor/bundle" ".cache" ".mypy_cache" ".icons" ".themes" "Videos" "Pictures")
FZF_IGNORE_GLOB=""
FZF_IGNORE_EXCLUDE=""
for p in "${FZF_IGNORE_DIRS[@]}"; do
	FZF_IGNORE_GLOB+="--glob '!**/$p/**' "
	FZF_IGNORE_EXCLUDE+="--exclude '*$p' "
done

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden $FZF_IGNORE_GLOB"

export FZF_DEFAULT_OPTS="
		--color=fg:#D4BE98,bg:#1D2021,hl:#eddeb5
		--color=fg+:#D4BE98,bg+:#1D2021,hl+:#eddeb5
		--color=border:#ea6962,header:#eddeb5,gutter:#1D2021
		--color=spinner:#7daea3,info:#7daea3,separator:#1D2021
		--color=pointer:#d8a657,marker:#ea6962,prompt:#d8a657"

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS=' --preview "batfile {}" --no-height'
export FZF_CTRL_R_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -H --maxdepth 5  $FZF_IGNORE_EXCLUDE --type d --follow --search-path '/etc' --search-path '/home/ml'"
export FZF_ALT_C_OPTS='--preview "exa -a -T -L 1 --color=always {}" --no-height'

export UV_THREADPOOL_SIZE=64
export PRETTIERD_DEFAULT_CONFIG=/home/ml/.prettierrc.json
export NPM_PACKAGES="${HOME}/.npm-packages"
export MANPATH="${MANPATH-$(manpath)}:${NPM_PACKAGES}/share/man"
export CHROME_PATH=/usr/bin/brave
export DICPATH=/usr/share/hunspell/
export JAVA_HOME=/usr/lib/jvm/java-17-graalvm
export PGDATA=/var/lib/postgres/data
export DOCKER_BUILDKIT=1

# pnpm
export PNPM_HOME="/home/ml/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

export LIBVA_DRIVER_NAME=nvidia
export MOZ_DISABLE_RDD_SANDBOX=1
export BUN_INSTALL="$HOME/.bun"
export TZ='America/Vancouver'

export PATH="/run/user/1000/fnm_multishells/414703_1682457091556/bin":$PATH
export FNM_ARCH="x64"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_LOGLEVEL="info"
export FNM_MULTISHELL_PATH="/run/user/1000/fnm_multishells/414703_1682457091556"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_DIR="/home/ml/.local/share/fnm"

export DB_UI_LOCAL=mysql://root:admin@127.0.0.1:3306/streamily_staging
export DB_UI_STAGING=mysql://root:1lFGdmIJT7cJ72RZeYuScjNDqZ5tBkAv5c@127.0.0.1:3307/streamily
export DB_UI_PRODUCTION=mysql://root:AnlZXLM3uNXUCJVG2SxYfXdCFr6PB6BOPN@127.0.0.1:3308/streamily
export DB_UI_COOKBOOK=mysql://root:admin@127.0.0.1:3306/cookbook

export GTK_THEME="Gruvbox-Material-Dark"
