#!/bin/bash

# History
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000

# Editor is vim
export VISUAL="/usr/bin/vim"
export EDITOR="/usr/bin/vim"
export FCEDIT="/usr/bin/vim"

# Use bat as a pager
export PAGER="bat --color=always --decorations=never --paging=always --theme=ansi"

# Man pages
export MANPAGER="less"
export MANWIDTH=110

# Less
export LESS='-J -i -x4'
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;33m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export TERMINAL=foot

# GPG and SSH
unset SSH_AGENT_PID
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"

# Update startup TTY
GPG_TTY="$(tty)"
gpg-connect-agent updatestartuptty /bye &>/dev/null
export GPG_TTY

# No mailcheck
export MAILCHECK=off

# Go
export GOPATH=""
export GO111MODULE="on"

# IP Regexp
export MATCH_IP='([0-9]{1,3}\.){3}[0-9]{1,3}'

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# bat theme
export BAT_THEME=ansi

# nnn
export NNN_OPENER='handlr open'
export NNN_PLUG='s:suedit'
export NNN_TMPFILE="$HOME/.config}/nnn/.lastd"

# fzf directories to ignore
FZF_IGNORE_DIRS=(".git" "build" "node_modules" ".fzf" ".npm-global" "vendor/bundle" ".cache" ".mypy_cache" ".icons" ".themes" "Videos" "Pictures")
FZF_IGNORE_GLOB=""
FZF_IGNORE_EXCLUDE=""
for p in "${FZF_IGNORE_DIRS[@]}"; do
	FZF_IGNORE_GLOB+="--glob '!**/$p/**' "
	FZF_IGNORE_EXCLUDE+="--exclude '*$p' "
done

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden $FZF_IGNORE_GLOB"

# FZF color settings
export FZF_DEFAULT_OPTS=" \
    --color=fg:#ECE1D7,bg:#292522,hl:#BD8183 \
    --color=fg+:#ECE1D7,bg+:#403A36,hl+:#BD8183 \
    --color=info:#7F91B2,prompt:#E49B5D,pointer:#BD8183 \
    --color=marker:#85B695,spinner:#D47766,header:#7B9695 \
    --color=gutter:#34302C,scrollbar:#A3A9CE \
    --color=border:#C1A78E"

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS=' --preview "batfile {}" --no-height'
export FZF_CTRL_R_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -H --maxdepth 5  $FZF_IGNORE_EXCLUDE --type d --follow --search-path '/etc' --search-path '/home/ml'"
export FZF_ALT_C_OPTS='--preview "exa -a -T -L 1 --color=always {}" --no-height'

export UV_THREADPOOL_SIZE=64
export PRETTIERD_DEFAULT_CONFIG=/home/ml/.prettierrc.json
export NPM_PACKAGES="${HOME}/.npm-global"
export MANPATH="${MANPATH-$(manpath)}:${NPM_PACKAGES}/share/man"
export DICPATH=/usr/share/hunspell/
export PGDATA=/var/lib/postgres/data
export DOCKER_BUILDKIT=1

# pnpm
export PNPM_HOME="/home/ml/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
export PATH="/home/ml/.npm-global/bin:$PATH"
# pnpm end

export BUN_INSTALL="$HOME/.bun"
export TZ='America/Vancouver'
export PATH="/run/user/1000/fnm_multishells/414703_1682457091556/bin":$PATH
export QT_QPA_PLATFORMTHEME=qt5ct

# fnm
FNM_PATH="/home/ml/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
	export PATH="$FNM_PATH:$PATH"
	eval "$(fnm env --version-file-strategy=recursive)"
fi

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export COLORTERM=truecolor
