#!/bin/bash

if [[ -n "${SSH_CLIENT}" || -n "${SSH_TTY}" ]]; then
	SESSION_TYPE=remote/ssh
fi

# ensure prompt has colors
export color_prompt=yes

# Get color sequence for exit code
get_exit_color() {
	if (($? > 0)); then
		EXIT_COLOR=31
	else
		EXIT_COLOR=35
	fi
}

# Format man page width
check_man_width() {
	if ((COLUMNS > 110)); then
		MANWIDTH=110
	else
		MANWIDTH="$((COLUMNS - 1))"
	fi
}

if [[ "${SESSION_TYPE}" =~ remote/ssh ]]; then
	# Prompt
	PS1='\n\[\033[01;34m\]\w\[\033[00m\]\n\[\033[0;37m\]$\[\033[00m\] '
	PS2="〉"
	PS4="> "
else
	# Make nice exit codes
	if [[ $DISPLAY ]]; then
		PROMPT_ICON='❱'
	else
		PROMPT_ICON='$'
	fi

	# Prompt
	PS1='\n\[\e[0;30m\]\w\n\[\e[1;${EXIT_COLOR}m\]  \[\e[0;30m\]${PROMPT_ICON}\[\e[0m\] '
	PS2="〉"
	PS4="> "
fi

# Prompt Command
declare -a PROMPT_COMMAND
PROMPT_COMMAND=(check_man_width get_exit_color)
export PROMPT_COMMAND
export MANWIDTH
