#!/bin/bash

if [[ -n "${SSH_CLIENT}" || -n "${SSH_TTY}" ]]; then
	SESSION_TYPE=remote/ssh
fi

# ensure prompt has colors
export color_prompt=yes

# get git branch
function get_git_branch() {
	SHELL_GIT_BRANCH="$(git branch --show-current 2>/dev/null)"
	if [[ "${SHELL_GIT_BRANCH}" != "" ]]; then
		SHELL_GIT_BRANCH=" ${SHELL_GIT_BRANCH}"
	fi
}

export __IS_FIRST_BASH_LOAD=1

# Get color sequence for exit code
function get_exit_color() {
	if ((__IS_FIRST_BASH_LOAD = 1)); then
		EXIT_COLOR=32
		__IS_FIRST_BASH_LOAD=0
	elif (($? > 0)); then
		EXIT_COLOR=31
	else
		EXIT_COLOR=32
	fi
}

# Format man page width
function check_man_width() {
	if ((COLUMNS > 110)); then
		MANWIDTH=110
	else
		MANWIDTH="$((COLUMNS - 1))"
	fi
}

if [[ "${SESSION_TYPE}" =~ remote/ssh ]]; then
	# Prompt
	PS1='\n\[\033[01;34m\]\w\[\033[00m\]\n\[\033[0;37m\]$\[\033[00m\] '
	PS2="+ "
	PS4="> "
else
	# Prompt
	PS1='\n\[\e[0;36m\]\w \[\e[0;35m\]${SHELL_GIT_BRANCH}\n\[\e[1;${EXIT_COLOR}m\]$ \[\e[0m\]'
	PS2="+ "
	PS4="> "
fi

# Prompt Command
declare -a PROMPT_COMMAND
PROMPT_COMMAND=(check_man_width get_exit_color get_git_branch)
export PROMPT_COMMAND
export MANWIDTH
