#!/bin/bash

# function to prepend to PATH
prepend_path() {
	case "$PATH" in
		*"$1"*) ;;
		*)
			PATH="$1:$PATH"
			;;
	esac
}

# ruby
prepend_path "$HOME/.local/share/gem/ruby/2.7.0/bin"

# fnm
prepend_path "$HOME/.fnm"

# rust
prepend_path "$HOME/.cargo/bin"

# go
prepend_path "/usr/local/go/bin"
prepend_path "$HOME/go/bin"

# local scripts dir
prepend_path "$HOME/.local/bin"
prepend_path "$HOME/.bin"

# fzf
source "$HOME/.fzf.bash"
