#!/bin/bash
function rmcontainer() {
	local container
	container="$(docker ps -a | grep "${1}" | cut -d' ' -f1 | head -1)"
	docker rm "${container}"
}

# Top disk usage
function ducks() {
	du -sh ./* | sort -hr | head -11
}

# Find a service port quickly
function wp() {
	grep --color=auto -E -i "^$1" /etc/services
}

# Which service for which port
function ws() {
	awk '{printf "%s\t", $2} {print $1}' /etc/services | grep -i --color=auto "^$1/"
}

# Easily edit script in PATH
function es() {
	local script prev
	script="$(which "$1")"
	prev="$PWD"
	cd "$(dirname "$script")" || exit 1
	vim "$script"
	cd "$prev" || exit 1
}

# Use fd instead of the default find
function _fzf_compgen_path() {
	rg --files --hidden --follow --glob "!.git/**" --glob "!build/**" --glob \
		"!node_modules/**" --glob "!vendor/bundle/**" "$1"
}

# Use fd to generate the list for directory completion
function _fzf_compgen_dir() {
	fd --type d --hidden --follow --exclude ".git" . "$1"
}

# fzf find a file to edit in vim
function s() {
	local file prev
	file="$(fzf --preview 'batfile {}' --no-height --ansi)"
	prev="$PWD"
	cd "$(dirname "$prev/$file")" || exit 1
	[[ "$file" ]] && vim "$prev/$file"
	cd "$prev" || exit 1
}

function r() {
	local file old
	old="$FZF_DEFAULT_COMMAND"
	FZF_DEFAULT_COMMAND="rg --files --glob '*.pdf' --glob '*.epub' $HOME/Books"
	file="$(fzf --no-height --ansi)"
	[[ "$file" ]] && zathura "$file" &>/dev/null &
	disown
	clear
	FZF_DEFAULT_COMMAND="$old"
}

function co() {
	local branch
	branch="$(git branch --sort=-committerdate | rg -v '^\*' | sed 's/[ *]*//' | fzf --no-height --ansi --preview 'git log --graph --pretty=oneline --abbrev-commit --color=always -n 15 {}')"
	[[ "${branch}" ]] && git checkout "${branch}"
}

# fzf find a man page
function m() {
	man -k . | fzf -q "$1" --prompt='man> ' \
		--preview $'echo {} | tr -d \'()\' | awk \'{printf "%s ", $2} {print $1}\' | xargs -r man' |
		tr -d '()' | awk '{printf "%s ", $2} {print $1}' | xargs -r man
}

# nnn
function n() {
	if [[ -n $NNNLVL ]] && ((${NNNLVL:-0} >= 1)); then
		echo "nnn is already running"
		return
	fi

	export NNN_TMPFILE="$HOME/.config/nnn/.lastd"
	nnn -dec "$@"

	if [[ -f $NNN_TMPFILE ]]; then
		. "$NNN_TMPFILE"
		rm -f "$NNN_TMPFILE" >/dev/null
	fi
}

function oz() {
	zathura "${@}" &>/dev/null &
	disown
	clear
}

function gam() {
	"${HOME}/.local/bin/gam/gam" "$@"
}

function stage() {
	local branch
	branch="$(git branch --show-current)"

	git checkout staging &&
		git pull &&
		git merge "$branch" &&
		git push
}

function osc7_cwd() {
	local strlen=${#PWD}
	local encoded=""
	local pos c o
	for ((pos = 0; pos < strlen; pos++)); do
		c=${PWD:$pos:1}
		case "$c" in
		[-/:_.!\'\(\)~[:alnum:]]) o="${c}" ;;
		*) printf -v o '%%%02X' "'${c}" ;;
		esac
		encoded+="${o}"
	done
	printf '\e]7;file://%s%s\e\\' "${HOSTNAME}" "${encoded}"
}

function fix_trackpad() {
	echo "0018:32AC:001B.0006" | sudo tee /sys/bus/hid/drivers/hid-sensor-hub/unbind
	sudo modprobe -r hid_multitouch
	sudo modprobe hid_multitouch
	sudo modprobe -r i2c_hid_acpi
	sudo modprobe i2c_hid_acpi
}

PROMPT_COMMAND=${PROMPT_COMMAND:+${PROMPT_COMMAND%;}; }osc7_cwd
