#!/bin/bash

# Confirm before overwriting
alias cp="cp -i"
alias mv="mv -i"

# ls replacement
alias ls="eza -a -s type"
alias ll="nnn -dec"
alias t="eza -aT -s type"

# cat replacement
alias cat="bat -pp --theme=ansi"
alias bat="bat --theme=ansi --tabs=4 --decorations never"

# easy typed common things
alias c="clear"
alias x="exit"
alias python="python3"
alias py="bpython"
alias js="node"
alias v="vim"
alias vi="vim"
alias dmesg='dmesg -H'
alias i='info --vi-keys'
alias p='pnpm'
alias info='info --vi-keys'
alias cman='lynx ~/Documents/gnu-c-manual.html'
alias se='sudoedit'
alias stanoff="xset -dpms"
alias stanon="xset +dpms"
alias sus="xset dpms force suspend"
alias adopt="bspc wm -o"

# Include hidden files by default
alias fd="fd -H"

# Crypto market stuff
alias btc="crypto-query btc"
alias eth="crypto-query eth"
alias ada="crypto-query ada"

# Switcher for optimus
alias opswitch="sudo /usr/bin/prime-switch"

# Color for grep, useful for logs
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Movement
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# Upgrade python packages
alias pip-upgrade="pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U"
alias g="gpg-connect-agent updatestartuptty /bye &>/dev/null"

# git
alias push="git push"
alias pull="git pull"
alias checkout="git checkout"
alias commit="git commit"
alias st="git status"

alias repl="clojure -M:repl/reloaded"
alias brepl="rlwrap bb socket-repl 1666"
alias pandock='docker run --rm -v "$(pwd):/data" -u $(id -u):$(id -g) pandoc/extra'
alias stripe="docker run --rm -it -v stripe-config://root/.config/stripe/ -v stripe-gpg://root/.gnupg/ -v stripe-pass://root/.password-store/ stripe-cli"

alias proddb='ssh -i "~/.ssh/st-prod-1.pem" -L 3308:st-prod-1-us-west-1.cluster-cz4qc0ygmyrt.us-west-1.rds.amazonaws.com:3306 ec2-user@ec2-52-53-72-199.us-west-1.compute.amazonaws.com -N'
alias proddb2='ssh -v -i "~/.ssh/st-prod-1.pem" -L 3308:st-prod-1-us-west-1.cluster-cz4qc0ygmyrt.us-west-1.rds.amazonaws.com:3306 ubuntu@ec2-54-177-172-105.us-west-1.compute.amazonaws.com -N'
alias stagingdb='ssh -i "~/.ssh/st-staging-1.pem" -L 3307:st-staging-1-us-west-1.cluster-cb4uoooy6nqd.us-west-1.rds.amazonaws.com:3306 ec2-user@ec2-204-236-166-169.us-west-1.compute.amazonaws.com -N'

alias prodredis='ssh -v -i "~/.ssh/st-prod-1.pem" -L 6379:ec-st-prod-1-us-west-1.jnv1yn.clustercfg.usw1.cache.amazonaws.com:6379 ubuntu@ec2-54-177-172-105.us-west-1.compute.amazonaws.com -N'

alias stagingredis='ssh -v -i "~/.ssh/st-staging-1.pem" -L 6379:ec-st-staging-1-us-west-1.ctek8e.clustercfg.usw1.cache.amazonaws.com:6379 ec2-user@ec2-204-236-166-169.us-west-1.compute.amazonaws.com -N'

alias redis-cli="docker run -it --network host --rm redis redis-cli"

alias mnt="udisksctl mount -b"
alias umnt="udisksctl unmount -b"
alias serve="python -m http.server 8080"
alias pick-color='grim -g "$(slurp -p)" -t ppm - | magick - -format "%[pixel:p{0,0}]" txt:-'
alias el="iamb"
