#!/bin/bash

# Confirm before overwriting
alias cp="cp -i"
alias mv="mv -i"

# ls replacement
alias ls="eza -a -s type"
alias ll="nnn -dec"
alias t="eza -aT -s type"

# cat replacement
alias cat="bat -pp --theme=ansi"
alias bat="bat --theme=ansi --tabs=4 --decorations never"

# easy typed common things
alias c="clear"
alias x="exit"
alias python="python3"
alias py="bpython"
alias js="node"
alias v="vim"
alias vi="vim"
alias dmesg='dmesg -H'
alias i='info --vi-keys'
alias p='pnpm'
alias info='info --vi-keys'
alias cman='lynx ~/Documents/gnu-c-manual.html'
alias se='sudoedit'
alias stanoff="xset -dpms"
alias stanon="xset +dpms"
alias sus="xset dpms force suspend"
alias adopt="bspc wm -o"

# Include hidden files by default
alias fd="fd -H"

# Crypto market stuff
alias btc="crypto-query btc"
alias eth="crypto-query eth"
alias ada="crypto-query ada"

# Switcher for optimus
alias opswitch="sudo /usr/bin/prime-switch"

# Color for grep, useful for logs
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Movement
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# Upgrade python packages
alias pip-upgrade="pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U"
alias g="gpg-connect-agent updatestartuptty /bye &>/dev/null"

# git
alias push="git push"
alias pull="git pull"
alias checkout="git checkout"
alias commit="git commit"
alias st="git status"

alias repl="clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version \"0.9.0\"} cider/cider-nrepl {:mvn/version \"0.28.4\"}}}' -m nrepl.cmdline --middleware '[\"cider.nrepl/cider-middleware\"]' --interactive"

alias pandock='docker run --rm -v "$(pwd):/data" -u $(id -u):$(id -g) pandoc/extra'
alias stripe="docker run --rm -it -v stripe-config://root/.config/stripe/ -v stripe-gpg://root/.gnupg/ -v stripe-pass://root/.password-store/ stripe-cli"

alias proddb='tsh ssh -L 3308:prod-aurora-us-west-1.cluster-cqioi60hyw7w.us-west-1.rds.amazonaws.com:3306 -N --proxy=secure.common.aws.us-west-1.streamily.com root@bastion-prod-1'
alias stagingdb='tsh ssh -L 3307:staging-aurora-us-west-1.cluster-cpe86pd9fivv.us-west-1.rds.amazonaws.com:3306 -N --proxy=secure.common.aws.us-west-1.streamily.com root@bastion-staging-1'

alias prodredis='tsh ssh -L 6379:redis.default.svc.cluster.local:6379 -N --proxy=secure.common.aws.us-west-1.streamily.com root@bastion-prod-1'

alias stagingredis='tsh ssh -L 6379:redis.default.svc.cluster.local:6379 -N --proxy=secure.common.aws.us-west-1.streamily.com root@bastion-staging-1'

alias redis-cli="docker run -it --network host --rm redis redis-cli"

alias mnt="udisksctl mount -b"
alias umnt="udisksctl unmount -b"
alias serve="python -m http.server 8080"
alias pick-color='grim -g "$(slurp -p)" -t ppm - | magick - -format "%[pixel:p{0,0}]" txt:-'
