#!/bin/bash

# Confirm before overwriting
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -I"

# ls replacement
alias ls="exa -aG --color=always -s type"
alias ll="exa -al --color=always -s type"
alias t="exa -aT --color=always -s type"

# cat replacement
alias cat="bat -pp --theme='ansi'"
alias bat="bat --theme='ansi' --tabs=4 --decorations never"

# easy typed common things
alias c="clear"
alias x="exit"
alias python="python3"
alias py="bpython"
alias js="node"
alias v="nvim"
alias vi="vim"
alias dmesg='dmesg -H'
alias i='info --vi-keys'
alias p='pnpm'
alias info='info --vi-keys'
alias cman='lynx ~/Documents/gnu-c-manual.html'
alias se='sudoedit'
alias stanoff="xset -dpms"
alias stanon="xset +dpms"
alias sus="xset dpms force suspend"
alias adopt="bspc wm -o"

# Include hidden files by default
alias fd="fd -H"

# Crypto market stuff
alias btc="crypto-query btc"
alias eth="crypto-query eth"
alias ada="crypto-query ada"

# Time chez Liz
alias liztime="TZ='US/Michigan' date"

# Switcher for optimus
alias opswitch="sudo /usr/bin/prime-switch"

# Color for grep, useful for logs
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Movement
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# Upgrade python packages
alias pip-upgrade="pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U"
alias suse="ssh -p 2222 moonlight@suse"
alias g="gpg-connect-agent updatestartuptty /bye &>/dev/null"
