#!/bin/sh

# Run a different xrandr depending on connected monitors
NUMMONS="$(xrandr --query | rg " connected" | cut -d" " -f1 | wc -l)"
if [ "$NUMMONS" -eq 2 ]; then
  # If I haz two monitors
  xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal \
    --output eDP-1-1 --mode 1920x1080 --pos 3840x1080 --rotate normal
	bspc monitor eDP-1-1 -d 6
	bspc monitor HDMI-0 -d 1 2 3 4 5
else
  # If I haz still two monitors but should have one
  if bspc query -M --names | grep HDMI-0 &>/dev/null ; then
    bspc monitor HDMI-0 -r
    xrandr --auto
    bspc wm -o
  fi
  # If i haz only one yay!
  xrandr --output eDP-1-1 --primary --rotate normal --pos 0x0 --mode 1920x1080
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6
fi

#LAUNCHERS
"$HOME/.config/bspwm/autostart.sh"

# Configure no border gaps
bspc config border_width   1
bspc config window_gap     0
bspc config top_padding    24
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0

#BSPWM configuration
bspc config single_monocle             false
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_follows_pointer      true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color   "#373c40"
bspc config active_border_color   "#373c40"
bspc config focused_border_color  "#984673"
bspc config presel_feedback_color "#89b482"

#Floating applications
bspc rule -a iwctl                   state=floating
bspc rule -a feh                     state=floating

#Tiled applications
bspc rule -a mpv                    state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura                state=tiled

#open applications on specific workspaces
bspc rule -a Gimp desktop='^5' state=floating
bspc rule -a OBS desktop='^6'  state=tiled

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
