#!/bin/sh

# Launcher function
run() {
	if ! pgrep "$1"; then
		"$@" &
	fi
}

# Run a different xrandr depending on connected monitors
LAPTOP="eDP-1-1"
EXTERNAL="HDMI-0"
export MONITORS
if xrandr | grep "$EXTERNAL connected"; then
	MONITORS="$EXTERNAL $LAPTOP"
	# If I haz two monitors
	xrandr --output $EXTERNAL --primary --mode 3840x2160 --pos 0x0 --rotate normal \
		--output $LAPTOP --mode 1920x1080 --pos 3840x1080 --rotate normal
	bspc monitor $EXTERNAL -d 1 2 3 4 5
	bspc monitor $LAPTOP -d 6
else
	# If I haz still two monitors but should have one
	OTHER_MONS="$(bspc query -M --names | grep -v $LAPTOP)"
	if [ "$OTHER_MONS" ]; then
		for m in $OTHER_MONS; do
			bspc monitor "$m" -r
			xrandr --output "$m" --off
		done
		bspc wm -r
		# bspc wm -o
	fi
	MONITORS="$LAPTOP"
	# If i haz only one yay!
	xrandr --output $LAPTOP --primary --rotate normal --pos 0x0 --mode 1920x1080
	bspc monitor $LAPTOP -d 1 2 3 4 5 6
fi

# Launch polybar
run "$HOME/.config/polybar/launch.sh"

# Start hotkey daemon
run sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc

# Start unclutter to hide cursor
run unclutter --timeout 1

# cursor fix
run xsetroot -cursor_name left_ptr

# Turn off key repeat
run xset r r off

# Map capslock to esc & ctrl
run setxkbmap -option ctrl:nocaps

# Applets
run numlockx on

# Compositor
run picom --experimental-backends --config "$HOME/.config/bspwm/picom.conf"

# Background image
run feh --bg-fill "$HOME/Pictures/mountain.jpg"

# Configure no border gaps
bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 24
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

#BSPWM configuration
bspc config single_monocle false
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color "#232330"
bspc config active_border_color "#333333"
bspc config focused_border_color "#ffc552"
bspc config presel_feedback_color "#333333"

#Floating applications
bspc rule -a iwctl state=floating
bspc rule -a l33th4x0rz state=floating
bspc rule -a feh state=floating

#Tiled applications
bspc rule -a mpv state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura state=tiled

#open applications on specific workspaces
bspc rule -a Gimp desktop='^5' state=floating
bspc rule -a OBS desktop='^6' state=tiled
