#!/usr/bin/env bash

printf ":fake-key -g gi" >"$QUTE_FIFO"
/home/ml/.fnm/aliases/default/bin/bw get item "$1" <<<"$2" \
	| jq .login.username,.login.password | while read -r line; do
	line="${line#\"}"
	line="${line%\"}"
	printf ":fake-key '%s'\n" "$line" >"$QUTE_FIFO"
	printf ":fake-key <tab>\n" >"$QUTE_FIFO"
done
