#!/usr/bin/env bash

HIST="$HOME/.local/share/qutebrowser/history.sqlite"
URL="$(sqlite3 "$HIST" <<<"select * from History" | cut -d'|' -f1 \
	| rofi -dmenu -p 'history search')"

if [ "$URL" ]; then
	echo "open $URL" >>"$QUTE_FIFO" || qutebrowser "$URL"
fi
