#!/bin/sh

NVIM=$HOME/.config/nvim/init.vim
BSPWM=$HOME/.config/bspwm/bspwmrc
SXHKD=$HOME/.config/bspwm/sxhkd/sxhkdrc
BASH=$HOME/.bashrc
KITTY=$HOME/.config/kitty/kitty.conf
POLYBAR=$HOME/.config/polybar/config

openConfig() {
	exec kitty --title "$2 - config editor" -e bash -c "vim $1"
}

case $1 in
nvim) openConfig "$NVIM" "$1" ;;
bspwm) openConfig "$BSPWM" "$1" ;;
sxhkd) openConfig "$SXHKD" "$1" ;;
bash) openConfig "$BASH" "$1" ;;
kitty) openConfig "$KITTY" "$1" ;;
polybar) openConfig "$POLYBAR" "$1" ;;
*) ;;
esac
